name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        celery-version: ['5.0']
        tornado-version: ['6.0']
        exclude:
          - celery-version: '5.0'
            python-version: '3.9'

    steps:
    - uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install celery==${{ matrix.celery-version }}
        pip install tornado==${{ matrix.tornado-version }}
        pip install -r requirements/default.txt
        pip install -r requirements/test.txt
        pip install -r requirements/dev.txt

    - name: Lint with pylint
      run: |
        pylint flower  --rcfile .pylintrc

    - name: Run unit tests
      run: |
        python -m flower --version
        python -m tests.unit.__main__

